branch-defaults:
  default:
    environment: server
    group_suffix: null
  master:
    environment: server
environment-defaults:
  server:
    branch: null
    repository: null
global:
  application_name: server
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
